Tarea nueva
joccreng/Ruby_Test pull request #1
Opened 2021-04-25 04:51 UTC by joccreng

2021-04-25 04:53 UTC, loldlm1 commented
Exelente viejo, asi si quedo bien :dancers:

2021-04-25 05:01 UTC, joccreng commented
> Exelente viejo, asi si quedo bien 
> 
> Pero aun asi sigue faltando algo, necesitamos que la logica sea un metodo que reciba el numero de la tabla
 


no entiendo eso jajaja

2021-04-27 20:13 UTC, loldlm1 requested changes

2021-04-27 20:13 UTC, loldlm1 commented on tabla_dividir.rb
> +end
Tienes el metodo creado pero por alguna razon estas dejando toda la logica fuera de el. La idea es que el metodo sea dinamico y lo ejecutes para que haga lo que queremos

2021-04-27 20:13 UTC, loldlm1 commented on tabla_dividir.rb
> +#end
Borra los comentarios por favor.

2021-04-27 20:25 UTC, loldlm1 requested changes

2021-04-27 20:25 UTC, loldlm1 commented on tabla_dividir.rb
> +puts tabla
Porfa haz que el metodo reciba el parametro que mandas mediante la consola y remueve el puts al ejecutar el metodo

2021-04-27 20:55 UTC, loldlm1 requested changes

2021-04-27 20:55 UTC, loldlm1 commented on tabla_dividir.rb
> +tabla 1
Estas pasando el argumento hardcoded, no es el numero que el usuario coloca en la consola :) 

PD: colocale los parentesis `tabla()`

2021-04-27 20:56 UTC, joccreng commented on tabla_dividir.rb
> +tabla 1
si moi, puedo colocar cualquier numero en la consola

2021-04-30 20:28 UTC, loldlm1 approved these changes

2021-04-30 20:29 UTC, merged